title: JinbangGuo's Homepage
page-top-title: JinbangGuo
top-section-bg-text: Be what you wanna be
home-subtitle: JinbangGuo&ensp;|&ensp;具身智能
copyright-text: '&copy; JinbangGuo 2023-2025. All Rights Reserved.'
